### ISSUE TITLE
[Community] Provide a pure web/JS wallet based on BIP 39

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/community#2]
##### SUMMARY

Consider providing a pure web/JS wallet that would support private key/account derivation from a [BIP 39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) mnemonic.

A good example would be how [Avalanche](https://avax.network) did it on the mnemonic and private key management side: https://wallet.avax.network/.

_Originally suggested by @fmanea in https://github.com/oasisprotocol/community/issues/1#issuecomment-723349908 and https://github.com/oasisprotocol/community/issues/1#issuecomment-723827378._

/cc @Bambarello

**Comment by expyri** [comment]
right !
