### ISSUE TITLE
[Community] Debonding interval length

### ISSUE THREAD

**Issue by expyri911** [oasisprotocol/community#3]
Hi, i think the debonding is really expensive ... may can you turn off ? it's really bad idea the debonding waiting time ...
Thx for you help !

https://mgt-corp.fr/

**Comment by tjanez** [comment]
Hi @expyri911,

> i think the debonding is really expensive ... may can you turn off ? it's really bad idea the debonding waiting time ...

are trying to say that the current [debonding inverval](https://docs.oasis.dev/general/mainnet/genesis-file#staking-and-rewards) of 336 epochs (approximately 14 days) to reclaim staked ROSE tokens is too long?

**Comment by expyri911** [comment]
> Hi @expyri911,
> 
> > i think the debonding is really expensive ... may can you turn off ? it's really bad idea the debonding waiting time ...
> 
> are trying to say that the current [debonding inverval](https://docs.oasis.dev/general/mainnet/genesis-file#staking-and-rewards) of 336 epochs (approximately 14 days) to reclaim staked ROSE tokens is too long?

Yes really too long, some people want undelegate and restake immediatly but they can't. i think it's better for oasis to remove this option !! :)

**Comment by expyri911** [comment]
i have an idea, may propose 2 options, 
1/ with unstake immeditaly but with fees and the fees are give to the node
2/ Reduce debonding to 7 days or less

thx

**Comment by vycl87** [comment]
In my opinion, debonding time can shorten the time a bit to be more binding on the Oasis community. In this way, the community can feel in a position to take action more easily.

**Comment by expyri** [comment]
yes pls so long ... pls reduce this or revome ...
